# This is a workflow to package and upload on CurseForge and GitHub Releases using BigWigs/Packager

name: Release

# Controls when the action will run.
on:
  # Package alpha version
  schedule:
    - cron: '0 6 * * *'   # at 06:00 UTC everyday
    - cron: '0 16 * * 0'  # at 16:00 UTC every sunday
  # Triggers the workflow on tag events
  push:
    tags:
      - '*.*.*'  # Matches tags like 1.2.3

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Check for changes since last tag
  check-changes:
    runs-on: ubuntu-slim
    outputs:
      release_type: ${{ steps.release_type.outputs.release_type }}
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}
    steps:
      - name: Determine the release type
        id: release_type
        shell: bash
        run: |
          if [ "${{ github.ref_type }}" = "tag" ] || [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "Release type: release (tag)"
            echo "release_type=release" >> $GITHUB_OUTPUT
          else
            echo "Release type: alpha (schedule/dispatch)"
            echo "release_type=alpha" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        if: steps.release_type.outputs.release_type == 'alpha'
        uses: actions/checkout@v6
        with:
           fetch-depth: 300

      - name: Reset to SHA that triggered the workflow
        if: steps.release_type.outputs.release_type == 'alpha'
        run: |
            git fetch --depth=300
            git reset --hard ${{ github.sha }}

      - name: Check for changes since last tag
        id: check_changes
        if: steps.release_type.outputs.release_type == 'alpha'
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "Last tag: $LAST_TAG"
          CHANGED_FILES=$(git diff --name-only $LAST_TAG HEAD)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes detected since last tag."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected since last tag:"
            echo "$CHANGED_FILES"
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

  build-windows:
    runs-on: windows-latest
    needs: check-changes
    if: needs.check-changes.outputs.release_type == 'release' || needs.check-changes.outputs.changes_detected == 'true'

    steps:
      - uses: actions/checkout@v6
        with:
           fetch-depth: 300

      - name: Reset to SHA that triggered the workflow
        run: git reset --hard ${{ github.sha }}

      - name: Database Parser for Retail
        timeout-minutes: 5
        run: |
          cd .contrib/Parser
          "Parser.exe" auto baseconfig=.config/retail/retail.config
        shell: cmd

      - name: Database Parser for Classic Era
        timeout-minutes: 5
        run: |
          cd .contrib/Parser
          "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/01 - Classic Era.config"
        shell: cmd

      - name: Database Parser for Season of Discovery
        timeout-minutes: 5
        run: |
          cd .contrib/Parser
          "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/01 - Classic SOD.config"
        shell: cmd

      - name: Database Parser for The Burning Crusade
        timeout-minutes: 5
        run: |
          cd .contrib/Parser
          "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/02 - TBC.config"
        shell: cmd

      - name: Database Parser for Wrath of the Lich King
        timeout-minutes: 5
        run: |
          cd .contrib/Parser
          "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/03 - Wrath.config"
        shell: cmd

      - name: Database Parser for Cataclysm
        timeout-minutes: 5
        run: |
          cd .contrib/Parser
          "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/04 - Cataclysm.config"
        shell: cmd

      - name: Database Parser for Mists of Pandaria
        timeout-minutes: 5
        run: |
          cd .contrib/Parser
          "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/05 - Mists of Pandaria.config"
        shell: cmd

      - uses: actions/upload-artifact@v7
        with:
            name: db-output  # Artifact name
            path: db/  # File path to upload
            retention-days: 7

  release-linux:
    runs-on: ubuntu-latest
    needs: build-windows

    steps:
      - uses: actions/checkout@v6
        with:
           fetch-depth: 300

      - name: Reset to SHA that triggered the workflow
        run: |
            git fetch --depth=300
            git reset --hard ${{ github.sha }}

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: db-output  # Name of the artifact to download
          path: db

      # once cloned, we just run the GitHub Action for the packager project
      - name: Package and release
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_KEY }}
